### ISSUE TITLE
Share our Security Control Profile

### ISSUE THREAD

**Issue by sylus** [canada-ca-terraform-modules/terraform-kubernetes-aks#4]
We should try to share our incredibly detailed SCP with the broader community.

**Comment by sylus** [comment]
![1b](https://user-images.githubusercontent.com/984304/66408217-879f5380-e9bc-11e9-8fe9-5b541dd6ab17.PNG)
![1c](https://user-images.githubusercontent.com/984304/66408218-879f5380-e9bc-11e9-999f-45adcec84c66.PNG)
![1a](https://user-images.githubusercontent.com/984304/66408219-8837ea00-e9bc-11e9-8ade-12787c7585cf.PNG)

**Comment by jemag** [comment]
README.md mentions : 
```markdown
We have recieved Authority to Operate and are happy to share our supporting documentation:

   - Concept of Operations
   - IT Security Controls (100+)
   - CIS Benchmarks
   - IBM Assessment
```
however I cannot seem to find the documentation within the repository. Were the bullets points meant as hyperlinks?

**Comment by sylus** [comment]
Hey @jemag if you work at a department you can request a copy by sending me an email and your department and we can send it. Unfortunately I still have to go through manual approval to share this across gov.

I'll update the README.md to say so as well!
